# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every day at 6h, 12h and 18h)
  schedule: [{cron: "0 6,12,18 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mateusfg7
          template: classic
          
          config_display: large
          config_timezone: America/Sao_Paulo
          config_animations: yes
          
          base: header, activity, repositories, metadata
          base_indepth: yes
          repositories_forks: yes
          repositories: 150
          repositories_affiliations: owner, collaborator
          commits_authoring: Mateus Felipe Gonçalves, Mateus Felipe, mateusfg7, mateusfg7@users.noreply.github.com
                    
          plugin_lines: yes
          plugin_lines_history_limit: 3
          
          plugin_languages: yes
          plugin_languages_ignored: scss, css, html, qml
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_details: lines
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          
          plugin_achievements: yes
          
          plugin_topics: yes
          plugin_topics_limit: 20
          plugin_topics_mode: icons
          plugin_topics_sort: starred
          
          plugin_traffic: yes
          
          plugin_code: yes
